### ISSUE TITLE
workflow run namespace: property for file checksums

### ISSUE THREAD

**Issue by simleo** [ResearchObject/ro-terms#14]
As discussed at the WRROC meeting

**Comment by simleo** [comment]
E.g. like https://schema.org/sha256, but we also need other popular ones

**Comment by stain** [comment]
see also 
https://datatracker.ietf.org/doc/html/rfc6920

From schemaorg/schemaorg#3162

[rfc6920](https://datatracker.ietf.org/doc/html/rfc6920) Naming things with hashes that establishes ways to identify checksum algorithms and representing their checksums as URIs.

Example:

    ni:///sha-256;f4OxZX_x_FO5LcGBSKHWXfwtSx-j1ncoSt3SABJtkGk 

identifies anything with the sha256 with the given base64-encoded checksum

alternatively in hex/human readable:

    nih:sha-256;7f83b1657ff1fc53b92dc18148a1d65dfc2d4b1fa3d677284addd200126d9069

(rfc6920 also specifies how to deal with truncation)

See [rfc6920 register](https://www.iana.org/assignments/named-information/named-information.xhtml) for more algorithms.

Combined with [arcp](https://s11.no/2018/arcp.html) URIs this is suggested already by RO-Crate for [Establishing a base URI](https://www.researchobject.org/ro-crate/1.1/appendix/relative-uris.html#establishing-a-base-uri-inside-a-zip-file) inside a ZIP file.
